### ISSUE TITLE
Patch 7.1 Issue?

### ISSUE THREAD

**Issue by althras** [Kruithne/TransmogTokens#20] opened 2016-10-26 13:12 UTC
I've never opened /tier before Patch 7.1, but I am now seeing only Tier 4-7 in drop down. Tier 4-6 tokens cannot be mouse overed (I'm not sure if that's normal), and Tier 7 tokens don't show up. Don't see anything else. When selecting Tier 7 in drop down, this error appears.

```
TransmogTokens\TransmogTokens-1.4.4.lua:290: bad argument #1 to 'pairs' (table expected, got number)
[C]: in function `pairs'
TransmogTokens\TransmogTokens-1.4.4.lua:290: in function `updateTierFrame'
TransmogTokens\TransmogTokens-1.4.4.lua:202: in function `func'
FrameXML\UIDropDownMenu.lua:787: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = 39492
(*temporary) = "table expected, got number"
 = <function> defined =[C]:-1
```

**Comment by althras** [comment] 2016-10-26 13:13
Apologies - this appears to be a duplicate of Issue 15

**Comment by Kruithne** [comment] 2016-10-26 21:36
The "/tier" command is a work-in-progress feature that never got finished due to time constraints. At some point I'll hopefully find the time to finish it, if someone else doesn't in the meantime.

Closing this as it's a duplicate of #15 as stated.

**Closed by Kruithne** 2016-10-26 21:36 UTC
